# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: Spasov Online
description: "The blog for pentesting, programming and technology"
keywords: 'blog, pentesting, programming, technology'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://www.github.com/WhiteLord
    - name: instagram
      url:
    - name: linkedin
      url: https://www.linkedin.com/in/georgi-spasov-b70403127
    - name: stackoverflow
      url:
    - name: twitter
      url: 
    - name: vk
      url:
home:
  section1: <h1>Spasov Online</h1>
  section2: <h2>A blog about cyber security, programming and technology</h2>
  section3: 
blog:
  cc_license: # A link to CC License of your choice, e.g. http://creativecommons.org/licenses/by-sa/4.0/.
  cc_license_image: # An image of your CC License, e.g. /assets/images/theme/cc-by-sa.png
  footer_content: A simple blog for professionals, enthusiasts and hobbyists. Share it with the widget on the left-hand side! 

disqus:
  shortname:
  public_key:
google_analytics:
addthis_public_id: ra-59caa8be11e40484

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
